meta_product_name: "Help Homeless"
meta_title: "Help Homeless - Together, We Make a Difference"
meta_description: "Promote upcoming volunteer events and opportunities, such as serving meals at a shelter or participating in a community cleanup."
meta_image: "cover.png" # should exist in `app/assets/images/`
